import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {promises as fs} from 'node:fs';
import {formState,validateForm,upload,download,selectField,checkField,submit,gate,safeError} from '../src/forms.js';
import {Sessions} from '../src/session.js';
let browser,p,server,origin,posts=0;
const fixtures='/mnt/data/sahbi-test-fixtures';
const html=`<form action='/submit' method='post'>
<label>Full Name: *<input name=full required></label>
<label>Email<input name=email type=email required></label>
<label>Password<input name=password type=password value=TOPSECRET></label>
<label>Resume: *<input name=resume type=file required accept='.pdf,.docx'></label>
<label>TEFL/C1/Degree: *<input name=proof type=file multiple></label>
<label for=language>Language</label><select id=language name=language required><option value=''>Choose</option><option value=ar>Arabic</option></select>
<label>Accept<input name=accept type=checkbox required></label>
<label>A<input type=radio name=level value=a required></label><label>B<input type=radio name=level value=b></label>
<button type=submit>Apply</button></form>`;
before(async()=>{await fs.mkdir(fixtures,{recursive:true});for(const f of ['test.pdf','test.docx'])await fs.copyFile(new URL('./fixtures/'+f,import.meta.url),fixtures+'/'+f);server=createServer((req,res)=>{res.setHeader('Content-Type','text/html');if(req.url==='/submit'){posts++;res.end('Application successfully submitted');}else if(req.url==='/file'){res.setHeader('Content-Disposition','attachment; filename="test.pdf"');fs.readFile(fixtures+'/test.pdf').then(x=>res.end(x));}else res.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({executablePath:process.env.SAHBI_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});p=await browser.newPage();});
after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
async function reset(keepSecret=false){await p.goto(origin);if(!keepSecret)await p.locator('[name=password]').evaluate(e=>e.remove());}
test('state: labels, mandatory hidden-style files, radio options, password redaction',async()=>{await reset(true);const s=await formState(p);assert.equal(s.fields.find(f=>f.name==='password').value,'[REDACTED]');assert.equal(s.fields.find(f=>f.name==='proof').required,true);assert.equal(s.fields.find(f=>f.name==='language').options.length,2);assert.equal(s.fields.find(f=>f.type==='radio').options.length,2);});
test('validation and submit block missing mandatory files without posting',async()=>{await reset();const v=await validateForm(p);assert(v.missing.some(f=>f.name==='proof'));const n=posts;assert.equal((await submit(p,{knownValuesConfirmed:true})).status,'validation_error');assert.equal(posts,n);});
test('actual PDF upload by label from /mnt/data',async()=>{await reset();const r=await upload(p,{label:'Resume: *',paths:[fixtures+'/test.pdf']});assert.equal(r.files[0].mimeType,'application/pdf');assert.equal(r.files[0].name,'test.pdf');});
test('actual DOCX upload by name and multiple files',async()=>{await reset();const r=await upload(p,{name:'proof',paths:[fixtures+'/test.docx',fixtures+'/test.pdf']});assert.equal(r.files.length,2);assert.equal(r.files[0].mimeType,'application/vnd.openxmlformats-officedocument.wordprocessingml.document');});
test('upload via associated text and selector',async()=>{await reset();await upload(p,{text:'Resume: *',paths:[fixtures+'/test.pdf']});await upload(p,{selector:'input[name=resume]',paths:[fixtures+'/test.docx']});});
test('host attachment relay checks actual bytes and declared metadata',async()=>{await reset();const buffer=await fs.readFile(fixtures+'/test.pdf');const attachment={name:'cv.pdf',size:buffer.length,mimeType:'application/pdf',base64:buffer.toString('base64')};assert((await upload(p,{name:'resume',attachments:[attachment]})).ok);await assert.rejects(upload(p,{name:'resume',attachments:[{...attachment,size:1}]}),/attachment_metadata_mismatch/);});
test('nonexistent, prohibited, malformed, multiple and unacceptable files fail',async()=>{await reset();await assert.rejects(upload(p,{name:'resume',paths:[fixtures+'/missing.pdf']}),/file_not_found/);await assert.rejects(upload(p,{name:'resume',paths:['/etc/passwd']}),/file_outside_upload_roots/);await assert.rejects(upload(p,{name:'resume',paths:[fixtures+'/test.pdf',fixtures+'/test.docx']}),/multiple_files_not_allowed/);await assert.rejects(upload(p,{name:'resume',attachments:[{name:'x.pdf',size:4,mimeType:'application/pdf',base64:'dGVzdA=='}]}),/mismatched_file_type/);await p.locator('[name=resume]').evaluate(e=>e.accept='.txt');await assert.rejects(upload(p,{name:'resume',paths:[fixtures+'/test.pdf']}),/site_file_type_not_allowed/);});
test('select native by visible text and value',async()=>{await reset();await selectField(p,{label:'Language',optionText:'Arabic'});assert.equal(await p.locator('select').inputValue(),'ar');await selectField(p,{name:'language',value:''});assert.equal(await p.locator('select').inputValue(),'');});
test('accessible dropdown selection',async()=>{await p.setContent(`<label id=l>City</label><button role=combobox aria-labelledby=l aria-controls=opts onclick="document.getElementById('opts').hidden=false">Choose</button><div id=opts hidden><div role=option data-value=paris onclick="this.setAttribute('aria-selected','true')">Paris</div></div>`);await selectField(p,{label:'City',optionText:'Paris'});assert.equal(await p.getByRole('option').getAttribute('aria-selected'),'true');});
test('check/uncheck and radio semantics',async()=>{await reset();await checkField(p,{label:'Accept'},true);await checkField(p,{name:'accept'},false);assert.equal(await p.locator('[name=accept]').isChecked(),false);await checkField(p,{label:'B'},true);assert(await p.getByLabel('B',{exact:true}).isChecked());await assert.rejects(checkField(p,{label:'B'},false),/radio_cannot/);await assert.rejects(checkField(p,{name:'level'},true),/ambiguous_target/);});
test('invalid email and site errors reported',async()=>{await reset();await p.locator('[name=email]').fill('wrong');let v=await validateForm(p);assert(v.missing.find(f=>f.name==='email').errors.includes('typeMismatch'));await p.locator('[name=full]').evaluate(e=>{e.setAttribute('aria-invalid','true');});v=await validateForm(p);assert(v.missing.find(f=>f.name==='full').errors.includes('aria_invalid'));});
test('download event returns existing exact path',async()=>{await p.goto(origin);await p.setContent(`<a href='${origin}/file'>Download</a>`);const r=await download(p,{text:'Download'},'/tmp/sahbi-download-tests');assert((await fs.stat(r.path)).size>100);await fs.rm(r.path);});
test('captcha and auth detected without bypass',async()=>{await p.setContent('<p>Verify you are human</p>');assert.equal(await gate(p),'captcha_required');assert.equal((await submit(p,{knownValuesConfirmed:true})).status,'captcha_required');await p.setContent('<input autocomplete=one-time-code>');assert.equal(await gate(p),'auth_required');});
test('complete factual test form submits once and detects confirmation',async()=>{await reset();await p.locator('[name=full]').fill('Synthetic Test');await p.locator('[name=email]').fill('test@example.invalid');await upload(p,{name:'resume',paths:[fixtures+'/test.pdf']});await upload(p,{name:'proof',paths:[fixtures+'/test.docx']});await selectField(p,{name:'language',value:'ar'});await checkField(p,{name:'accept'},true);await checkField(p,{label:'A'},true);assert.equal((await submit(p,{knownValuesConfirmed:false})).status,'blocked');const n=posts;const r=await submit(p,{knownValuesConfirmed:true});assert.equal(r.status,'submitted');assert.equal(posts,n+1);});
test('unknown redirect is not claimed as success',async()=>{await p.setContent(`<form><button type=submit>Apply</button></form><script>document.querySelector('form').onsubmit=e=>{e.preventDefault();history.pushState({},'', '/unknown');}</script>`);const r=await submit(p,{knownValuesConfirmed:true,timeoutMs:500});assert.equal(r.status,'blocked');assert.equal(r.retrySafe,false);});
test('exception output never leaks selector/value/token',()=>{assert(!JSON.stringify(safeError(new Error('fill password TOPSECRET token=abc'))).includes('TOPSECRET'));});
test('persistent cookies/localStorage, isolated profiles, targeted reset and actual tab crash recovery',async()=>{
 const root=await fs.mkdtemp('/tmp/sahbi-profile-');let s=new Sessions(root);let r=await s.current();const one=await s.page();await one.goto(origin);await one.evaluate(()=>localStorage.setItem('test','stored'));await r.context.addCookies([{name:'test',value:'cookie',url:origin}]);const two=await r.context.newPage();await two.goto(origin+'/second');r.page=two;
 const cdp=await r.context.newCDPSession(two);await cdp.send('Page.crash').catch(()=>{});await s.page();assert(!one.isClosed());assert.equal(r.context.pages().length,2);assert(s.events.some(e=>e.status==='recovered'));assert.equal(await one.evaluate(()=>localStorage.getItem('test')),'stored');
 await s.close();s=new Sessions(root);r=await s.current();const restored=await s.page();assert.equal(await restored.evaluate(()=>localStorage.getItem('test')),'stored');assert((await r.context.cookies(origin)).some(c=>c.name==='test'));assert.equal(r.context.pages().length,2);
 const isolated=await s.use('example.com','other');const separate=await s.page();await separate.goto(origin);assert.equal(await separate.evaluate(()=>localStorage.getItem('test')),null);await s.reset(isolated.profile);assert(!restored.isClosed());await s.close();await fs.rm(root,{recursive:true,force:true});
});
test('remote CDP disconnect preserves engine tabs and data',async()=>{
 const net=await import('node:net');const tmpServer=net.createServer();await new Promise(r=>tmpServer.listen(0,'127.0.0.1',r));const port=tmpServer.address().port;await new Promise(r=>tmpServer.close(r));
 const engine=await chromium.launch({executablePath:process.env.SAHBI_EXECUTABLE_PATH,args:['--no-sandbox',`--remote-debugging-port=${port}`]});
 const original=await engine.newPage();await original.goto(origin);
 const dir=await fs.mkdtemp('/tmp/sahbi-cdp-');const old=process.env.SAHBI_CDP_URL;process.env.SAHBI_CDP_URL=`http://127.0.0.1:${port}`;
 try{const s=new Sessions(dir);const attached=await s.page();assert.equal(attached.url(),origin+'/');await s.close();assert(!original.isClosed());assert.equal(await original.title(),'');}finally{if(old)process.env.SAHBI_CDP_URL=old;else delete process.env.SAHBI_CDP_URL;await engine.close();await fs.rm(dir,{recursive:true,force:true});}
});
